"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.
"""

from pathlib import Path
from datetime import timedelta
import os

from dotenv import load_dotenv


# --------------------------------------------------
# BASE DIRECTORY
# --------------------------------------------------

BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")


# --------------------------------------------------
# SECURITY
# --------------------------------------------------

SECRET_KEY = os.getenv("SECRET_KEY")

DEBUG = os.getenv("DEBUG", "False") == "True"


ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "identityhub-5ygq.onrender.com",
]



# --------------------------------------------------
# APPLICATIONS
# --------------------------------------------------

INSTALLED_APPS = [

    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "django.contrib.sites",


    # Third party
    "rest_framework",

    "rest_framework.authtoken",

    "rest_framework_simplejwt.token_blacklist",

    "corsheaders",

    "axes",

    "dj_rest_auth",

    "allauth",

    "allauth.account",

    "allauth.socialaccount",

    "allauth.socialaccount.providers.google",


    # Local
    "users",

]


SITE_ID = 1



# --------------------------------------------------
# MIDDLEWARE
# --------------------------------------------------

MIDDLEWARE = [

    "corsheaders.middleware.CorsMiddleware",

    "django.middleware.security.SecurityMiddleware",

    "whitenoise.middleware.WhiteNoiseMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",

    "django.middleware.common.CommonMiddleware",

    "django.middleware.csrf.CsrfViewMiddleware",

    "django.contrib.auth.middleware.AuthenticationMiddleware",

    "allauth.account.middleware.AccountMiddleware",

    "axes.middleware.AxesMiddleware",

    "django.contrib.messages.middleware.MessageMiddleware",

    "django.middleware.clickjacking.XFrameOptionsMiddleware",

]



ROOT_URLCONF = "config.urls"



# --------------------------------------------------
# TEMPLATES
# --------------------------------------------------

TEMPLATES = [

    {

        "BACKEND": "django.template.backends.django.DjangoTemplates",

        "DIRS": [],

        "APP_DIRS": True,

        "OPTIONS": {

            "context_processors": [

                "django.template.context_processors.request",

                "django.contrib.auth.context_processors.auth",

                "django.contrib.messages.context_processors.messages",

            ],

        },

    },

]



WSGI_APPLICATION = "config.wsgi.application"



# --------------------------------------------------
# DATABASE
# SQLite for personal deployment
# --------------------------------------------------

DATABASES = {

    "default": {

        "ENGINE": "django.db.backends.sqlite3",

        "NAME": BASE_DIR / "db.sqlite3",

    }

}



# --------------------------------------------------
# PASSWORD VALIDATION
# --------------------------------------------------

AUTH_PASSWORD_VALIDATORS = [

    {
        "NAME":
        "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },

    {
        "NAME":
        "django.contrib.auth.password_validation.MinimumLengthValidator",
    },

    {
        "NAME":
        "django.contrib.auth.password_validation.CommonPasswordValidator",
    },

    {
        "NAME":
        "django.contrib.auth.password_validation.NumericPasswordValidator",
    },

]



# --------------------------------------------------
# CUSTOM USER
# --------------------------------------------------

AUTH_USER_MODEL = "users.User"



# --------------------------------------------------
# AUTHENTICATION
# --------------------------------------------------

AUTHENTICATION_BACKENDS = [

    "axes.backends.AxesStandaloneBackend",

    "django.contrib.auth.backends.ModelBackend",

]



# --------------------------------------------------
# REST FRAMEWORK
# --------------------------------------------------

REST_FRAMEWORK = {

    "DEFAULT_AUTHENTICATION_CLASSES": (

        "rest_framework_simplejwt.authentication.JWTAuthentication",

    ),

}



# --------------------------------------------------
# JWT
# --------------------------------------------------

SIMPLE_JWT = {

    "ACCESS_TOKEN_LIFETIME": timedelta(seconds=30),

    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),

    "ROTATE_REFRESH_TOKENS": True,

    "BLACKLIST_AFTER_ROTATION": True,

}



# --------------------------------------------------
# AXES
# --------------------------------------------------

AXES_FAILURE_LIMIT = 5

AXES_COOLOFF_TIME = 1

AXES_RESET_ON_SUCCESS = True

AXES_ENABLED = False



# --------------------------------------------------
# ALLAUTH
# --------------------------------------------------

ACCOUNT_LOGIN_METHODS = {"username"}


ACCOUNT_SIGNUP_FIELDS = [

    "email*",

    "username*",

    "password1*",

    "password2*",

]


ACCOUNT_EMAIL_VERIFICATION = "none"



# --------------------------------------------------
# LANGUAGE
# --------------------------------------------------

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True



# --------------------------------------------------
# STATIC FILES
# --------------------------------------------------

STATIC_URL = "/static/"

STATIC_ROOT = BASE_DIR / "staticfiles"


STATICFILES_STORAGE = (

    "whitenoise.storage.CompressedManifestStaticFilesStorage"

)



# --------------------------------------------------
# CORS
# --------------------------------------------------

CORS_ALLOWED_ORIGINS = [

    "http://localhost:5173",

    "https://identityhub-frontend.onrender.com",

]



# --------------------------------------------------
# CSRF
# --------------------------------------------------

CSRF_TRUSTED_ORIGINS = [

    "https://identityhub-frontend.onrender.com",

    "https://identityhub-5ygq.onrender.com",

]



# --------------------------------------------------
# DEFAULT FIELD
# --------------------------------------------------

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"



# --------------------------------------------------
# GOOGLE OAUTH
# --------------------------------------------------

SOCIALACCOUNT_PROVIDERS = {

    "google": {

        "APP": {

            "client_id": os.getenv("GOOGLE_CLIENT_ID"),

            "secret": os.getenv("GOOGLE_CLIENT_SECRET"),

            "key": "",

        },


        "SCOPE": [

            "profile",

            "email",

        ],


        "AUTH_PARAMS": {

            "access_type": "online",

        },

    }

}